version: '3.8'

services:
  # Backend (API)
  app:
    build: .
    container_name: backend_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    # Comando para rodar a API
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend (Streamlit)
  frontend:
    build: .
    container_name: frontend_ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      # O frontend precisa saber onde a API est√° DENTRO da rede do Docker
      - API_URL=http://app:8000 
    depends_on:
      - app
    # üëá AQUI EST√Å A M√ÅGICA QUE CONSERTA:
    command: streamlit run frontend.py --server.address=0.0.0.0 --server.port=8501